### PR TITLE
feat: fixes from both PRs for Blender v4+

### PR DESCRIPTION
**Pull request by Cygnusfear**
This will make the plugin Blender 4 compatible 🤙 chevvbre

Includes changes from both unmerged PR's, all credits go to:
- [GifCo](https://github.com/GifCo) https://github.com/ReshotAI/gaussian-splatting-blender-addon/pull/14
- https://github.com/Wladefant https://github.com/ReshotAI/gaussian-splatting-blender-addon/pull/13

### CODE REVIEW

**Comment by Pfaeff** [comment]
Good job. It seems to work better than the other two PRs, but when I try it, I get perfect circular discs instead of proper gaussian splats. So something still isn't quite right.

**Comment by MikeTkachuk** [comment]
is "as point cloud" box checked?

**Comment by alexandre01** [comment]
Merged in #18, thanks for your work @Cygnusfear! 🙏

**Comment by Pfaeff** [comment]
> is "as point cloud" box checked?

I now see the errors of my ways 😅 Thank you.

**Pull request closed without merging**
